// ==========================================
// CANONICAL ATS RESUME SKELETON (main.template.typ)
// ==========================================
// Copy this file to `main.typ` and replace placeholder header details.
// Variables from tailored.typ will be automatically injected below.

#import "tailored.typ": target-role, summary, skills, experience

#set page(
  paper: "a4",
  margin: (x: 1.2cm, top: 0.85cm, bottom: 0.85cm),
)

#set text(
  font: "Liberation Sans",
  size: 9.1pt,
  fill: rgb("#111111"),
  lang: "en",
)

#set par(justify: false, leading: 0.50em)

// Strict Canonical Headings
#show heading.where(level: 1): it => {
  v(0.35em)
  text(weight: "bold", size: 9.8pt)[#upper(it.body)]
  v(-0.38em)
  line(length: 100%, stroke: 0.5pt + rgb("#666666"))
  v(0.12em)
}

// --- HEADER (Customize with your personal contact info) ---
#align(center)[
  #text(weight: "bold", size: 14pt)[YOUR FULL NAME]\
  #v(-0.25em)
  #text(weight: "bold", size: 9.5pt, fill: rgb("#333333"))[#target-role]\
  #v(0.1em)
  #text(size: 8.5pt)[
    City, Country · #link("mailto:your.email@example.com")[your.email\@example.com] · +123 456 7890 · #link("https://linkedin.com/in/yourprofile")[linkedin.com/in/yourprofile]
  ]\
  #text(size: 8pt, fill: rgb("#444444"))[
    Full Work Authorization · Languages: English (Fluent), [Language 2]
  ]
]

// --- DYNAMIC SECTIONS (Generated by ATS Tailor Engine) ---
= Professional Summary
#summary

= Skills
#skills

= Professional Experience
#experience

// --- STATIC SECTIONS (Customize with your static details) ---
= Projects & Key Initiatives
- *Featured Project Name* #h(1fr) 2022 – Present\
  Description of the project impact, core architecture, and measurable outcomes.

= Education & Certifications
- *Degree Name in Field* — University Name #h(1fr) 2018 – 2022
- *Industry Certification Name* — Issuing Body #h(1fr) 2023
